// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjC6lZserxykZa8w-XoNeeZ2p68FRru-g',
    appId: '1:485348936757:web:a43727af88700ec706357c',
    messagingSenderId: '485348936757',
    projectId: 'bus-tracking-system-fedfe',
    authDomain: 'bus-tracking-system-fedfe.firebaseapp.com',
    storageBucket: 'bus-tracking-system-fedfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfvFh6obIzAJfHVoSlE4Q5ydIlSHI60s',
    appId: '1:485348936757:android:462bca0960bd76b906357c',
    messagingSenderId: '485348936757',
    projectId: 'bus-tracking-system-fedfe',
    storageBucket: 'bus-tracking-system-fedfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5NrdnshpDNRp6m5lIByxA_3Xu_gtwYw',
    appId: '1:485348936757:ios:b017805f2967561a06357c',
    messagingSenderId: '485348936757',
    projectId: 'bus-tracking-system-fedfe',
    storageBucket: 'bus-tracking-system-fedfe.firebasestorage.app',
    iosClientId: '485348936757-rifk6qntpap9p3tbilvd22vvdpjbgp3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh5NrdnshpDNRp6m5lIByxA_3Xu_gtwYw',
    appId: '1:485348936757:ios:b017805f2967561a06357c',
    messagingSenderId: '485348936757',
    projectId: 'bus-tracking-system-fedfe',
    storageBucket: 'bus-tracking-system-fedfe.firebasestorage.app',
    iosClientId: '485348936757-rifk6qntpap9p3tbilvd22vvdpjbgp3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjC6lZserxykZa8w-XoNeeZ2p68FRru-g',
    appId: '1:485348936757:web:eeb88850925663d706357c',
    messagingSenderId: '485348936757',
    projectId: 'bus-tracking-system-fedfe',
    authDomain: 'bus-tracking-system-fedfe.firebaseapp.com',
    storageBucket: 'bus-tracking-system-fedfe.firebasestorage.app',
  );

}