// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxcBw91HexvnXJgpUrOa3XnFe8GTYp4o',
    appId: '1:39552685714:web:8665dbeef03ce58e78f84b',
    messagingSenderId: '39552685714',
    projectId: 'busbee-udaya-2026',
    authDomain: 'busbee-udaya-2026.firebaseapp.com',
    storageBucket: 'busbee-udaya-2026.firebasestorage.app',
    measurementId: 'G-J4Z7W3BNHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgNQ9RVHKrcL25vqVHkxgLaFRKbM-hhY',
    appId: '1:39552685714:android:0e299dc934e00d1878f84b',
    messagingSenderId: '39552685714',
    projectId: 'busbee-udaya-2026',
    storageBucket: 'busbee-udaya-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUtOH-3sLi12H_1TaEpFpD1U9XgQkqLc',
    appId: '1:39552685714:ios:343c7d76473d725678f84b',
    messagingSenderId: '39552685714',
    projectId: 'busbee-udaya-2026',
    storageBucket: 'busbee-udaya-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUtOH-3sLi12H_1TaEpFpD1U9XgQkqLc',
    appId: '1:39552685714:ios:343c7d76473d725678f84b',
    messagingSenderId: '39552685714',
    projectId: 'busbee-udaya-2026',
    storageBucket: 'busbee-udaya-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjxcBw91HexvnXJgpUrOa3XnFe8GTYp4o',
    appId: '1:39552685714:web:15b27513f3a4f4f278f84b',
    messagingSenderId: '39552685714',
    projectId: 'busbee-udaya-2026',
    authDomain: 'busbee-udaya-2026.firebaseapp.com',
    storageBucket: 'busbee-udaya-2026.firebasestorage.app',
    measurementId: 'G-3WTVHWGX54',
  );
}
